# Filterbank config
filterbank:
  n_filters: 512  #Number of filters
  kernel_size: 512  #512 #window_size
  stride: 256  #hop_length
  sample_rate: 16000 
# Training config
training:
  epochs: 100
  batch_size: 64
  num_workers: 4
  half_lr: n
  early_stop: n
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  #weight_decay: 0.0001
  #amsgrad: True
# Data config
data:
  json_dir: dataset_own/mi_smi_polqa_ae/
  val_prop: 0.2
